/**
 * Regenerates `.gen/migrations.gen.ts` for the package it's run from (cwd),
 * embedding its `drizzle/` journal and SQL files via import attributes so
 * `bun build --compile` bundles them into the binary instead of leaving them
 * as files a compiled binary can't find on disk.
 *
 * Invoked as the `deskkit gen-migrations` subcommand (`bun -b deskkit
 * gen-migrations`), after `drizzle-kit generate`.
 */
import { Effect, FileSystem, Path, Schema } from 'effect';
import { Command } from 'effect/unstable/cli';
import { Journal } from './migrations.ts';

/** Any failure formatting the generated bundle with biome. */
export class BiomeFormatError extends Schema.TaggedErrorClass<BiomeFormatError>()(
	'BiomeFormatError',
	{ cause: Schema.Defect() },
) {}

const generateMigrationsBundle = Effect.gen(function* () {
	const fs = yield* FileSystem.FileSystem;
	const path = yield* Path.Path;

	const journalPath = path.join(
		process.cwd(),
		'drizzle',
		'meta',
		'_journal.json',
	);
	const outPath = path.join(process.cwd(), '.gen', 'migrations.gen.ts');

	const journalContents = yield* fs.readFileString(journalPath);
	const journal = yield* Schema.decodeUnknownEffect(
		Schema.fromJsonString(Journal),
	)(journalContents);

	// The emitted specifiers below are source text inside generated `import`
	// statements, so they must stay POSIX-separated no matter which OS this
	// runs on. Resolve them with the Path service's built-in POSIX layer
	// rather than whichever host-native one the ambient environment provides.
	const posixPath = yield* Path.Path.pipe(Effect.provide(Path.layer));

	const imports: string[] = [];
	const filesEntries: string[] = [];

	for (const entry of journal.entries) {
		const relSqlPath = posixPath.join('..', 'drizzle', `${entry.tag}.sql`);
		const varName = `m${String(entry.idx).padStart(4, '0')}`;
		imports.push(
			`import ${varName} from "${relSqlPath}" with { type: "text" };`,
		);
		filesEntries.push(`\t"${entry.tag}": ${varName}`);
	}

	const relJournalPath = posixPath.join(
		'..',
		'drizzle',
		'meta',
		'_journal.json',
	);

	const content = `// @ts-nocheck
// Auto-generated by deskkit's gen-migrations — do not edit manually
import journal from "${relJournalPath}" with { type: "json" };
${imports.join('\n')}

export default {
	journal: journal as { entries: { idx: number; when: number; tag: string; breakpoints: boolean }[] },
	files: {
${filesEntries.join(',\n')}
	} as Record<string, string>,
};
`;

	yield* fs.makeDirectory(path.dirname(outPath), { recursive: true });
	yield* fs.writeFileString(outPath, content);

	// Bring the generated file in line with the consuming repo's biome config
	// (tabs, sorted imports, trailing commas) so `check:lint` doesn't flag its
	// own output.
	yield* Effect.try({
		try: () =>
			Bun.spawnSync(['bunx', 'biome', 'check', '--write', outPath], {
				stdout: 'inherit',
				stderr: 'inherit',
			}),
		catch: (cause) => new BiomeFormatError({ cause }),
	});

	yield* Effect.logInfo(`Generated ${outPath}`);
});

export const genMigrationsCommand = Command.make(
	'gen-migrations',
	{},
	() => generateMigrationsBundle,
).pipe(
	Command.withDescription(
		"Regenerates .gen/migrations.gen.ts from the cwd's drizzle/ journal and SQL files.",
	),
);
