/**
 * Regenerates `.gen/migrations.gen.ts` for the package it's run from (cwd),
 * embedding its `drizzle/` migration SQL via import attributes so
 * `bun build --compile` bundles it into the binary instead of leaving it
 * as files a compiled binary can't find on disk.
 *
 * Invoked as the `deskkit gen-migrations` subcommand (`bun -b deskkit
 * gen-migrations`), after `drizzle-kit generate`. Only reads drizzle-kit
 * 1.x's migrations layout — a repo still on the pre-1.x layout (a
 * `meta/_journal.json`) needs `drizzle-kit up` first, and fails with a
 * message saying so rather than a parse error.
 */
import { Console, Effect, FileSystem, Path, Schema } from 'effect';
import { Command } from 'effect/unstable/cli';
import { readMigrationLayout } from './migration-layout.ts';

/** Any failure reading the migrations folder or writing the generated bundle. */
export class GenMigrationsError extends Schema.TaggedError<GenMigrationsError>()(
	'GenMigrationsError',
	{ cause: Schema.Defect() },
) {}

const generateMigrationsBundle = Effect.gen(function* () {
	const fs = yield* FileSystem.FileSystem;
	const path = yield* Path.Path;

	const migrationsDir = path.join(process.cwd(), 'drizzle');
	const outPath = path.join(process.cwd(), '.gen', 'migrations.gen.ts');

	const entries = yield* readMigrationLayout(migrationsDir).pipe(
		Effect.catchTags({
			LegacyMigrationsLayoutError: (error) =>
				Effect.gen(function* () {
					yield* Console.error(
						`${error.migrationsDir} is still on drizzle-kit's pre-1.x migrations layout (a meta/_journal.json). Run \`drizzle-kit up\` to convert it, then re-run gen-migrations.`,
					);
					return yield* error;
				}),
			MalformedMigrationNameError: (error) =>
				Effect.gen(function* () {
					yield* Console.error(
						`${error.migrationsDir}/${error.name} doesn't look like a drizzle-kit migration directory — expected a 14-digit timestamp prefix (e.g. 20260811173454_tidy_wendell_rand). gen-migrations can't safely order it; if this wasn't hand-edited, re-run drizzle-kit generate.`,
					);
					return yield* error;
				}),
		}),
	);

	const imports: string[] = [];
	const migrationEntries: string[] = [];

	entries.forEach((entry, index) => {
		// This specifier gets emitted into the generated file's `import`
		// statement, so it must stay POSIX-separated regardless of host
		// platform — deliberately not built with `path.join`, which would
		// emit `\` on Windows.
		const relSqlPath = `../drizzle/${entry.name}/migration.sql`;
		const varName = `m${String(index).padStart(4, '0')}`;
		imports.push(
			`import ${varName} from '${relSqlPath}' with { type: 'text' };`,
		);
		migrationEntries.push(`\t\t{ name: '${entry.name}', sql: ${varName} },`);
	});

	const content = `// @ts-nocheck
// Auto-generated by deskkit's gen-migrations — do not edit manually

${imports.join('\n')}

export default {
	migrations: [
${migrationEntries.join('\n')}
	],
};
`;

	yield* fs.makeDirectory(path.dirname(outPath), { recursive: true });
	yield* fs.writeFileString(outPath, content);

	yield* Console.log(`Generated ${outPath}`);
}).pipe(Effect.mapError((cause) => new GenMigrationsError({ cause })));

export const genMigrationsCommand = Command.make(
	'gen-migrations',
	{},
	() => generateMigrationsBundle,
).pipe(
	Command.withDescription(
		"Regenerates .gen/migrations.gen.ts from the cwd's drizzle/ migrations folder (drizzle-kit 1.x layout).",
	),
);
