/**
 * Regenerates `.gen/migrations.gen.ts` for the package it's run from (cwd),
 * embedding its `drizzle/` journal and SQL files via import attributes so
 * `bun build --compile` bundles them into the binary instead of leaving them
 * as files a compiled binary can't find on disk.
 *
 * Invoked as the `deskkit gen-migrations` subcommand (`bun -b deskkit
 * gen-migrations`), after `drizzle-kit generate`.
 */
import { Console, Effect, FileSystem, Path, Schema } from 'effect';
import { Command } from 'effect/unstable/cli';
import { Journal } from './migrations.ts';

/** Any failure reading the journal or writing the generated bundle. */
export class GenMigrationsError extends Schema.TaggedErrorClass<GenMigrationsError>()(
	'GenMigrationsError',
	{ cause: Schema.Defect() },
) {}

const generateMigrationsBundle = Effect.gen(function* () {
	const fs = yield* FileSystem.FileSystem;
	const path = yield* Path.Path;

	const journalPath = path.join(
		process.cwd(),
		'drizzle',
		'meta',
		'_journal.json',
	);
	const outPath = path.join(process.cwd(), '.gen', 'migrations.gen.ts');

	const journalContent = yield* fs.readFileString(journalPath);
	const journal = yield* Schema.decodeUnknownEffect(
		Schema.fromJsonString(Journal),
	)(journalContent);

	const imports: string[] = [];
	const filesEntries: string[] = [];

	for (const entry of journal.entries) {
		// These specifiers get emitted into the generated file's `import`
		// statements, so they must stay POSIX-separated regardless of host
		// platform — deliberately not built with `path.join`, which would
		// emit `\` on Windows.
		const relSqlPath = `../drizzle/${entry.tag}.sql`;
		const varName = `m${String(entry.idx).padStart(4, '0')}`;
		imports.push(
			`import ${varName} from '${relSqlPath}' with { type: 'text' };`,
		);
		filesEntries.push(`\t\t'${entry.tag}': ${varName},`);
	}

	// Biome's `organizeImports` assist sorts import specifiers lexically, and
	// every SQL import starts with a zero-padded digit while this one starts
	// with "meta" — digits always sort first, so this stays last.
	const relJournalPath = '../drizzle/meta/_journal.json';

	const content = `// @ts-nocheck
// Auto-generated by deskkit's gen-migrations — do not edit manually

${[...imports, `import journal from '${relJournalPath}' with { type: 'json' };`].join('\n')}

export default {
	journal: journal as { entries: { idx: number; when: number; tag: string; breakpoints: boolean }[] },
	files: {
${filesEntries.join('\n')}
	} as Record<string, string>,
};
`;

	yield* fs.makeDirectory(path.dirname(outPath), { recursive: true });
	yield* fs.writeFileString(outPath, content);

	yield* Console.log(`Generated ${outPath}`);
}).pipe(Effect.mapError((cause) => new GenMigrationsError({ cause })));

export const genMigrationsCommand = Command.make(
	'gen-migrations',
	{},
	() => generateMigrationsBundle,
).pipe(
	Command.withDescription(
		"Regenerates .gen/migrations.gen.ts from the cwd's drizzle/ journal and SQL files.",
	),
);
