// @ts-nocheck
// Auto-generated by deskkit's gen-migrations — do not edit manually

import m0000 from '../drizzle/0000_little_fallen_one.sql' with { type: 'text' };
import journal from '../drizzle/meta/_journal.json' with { type: 'json' };

export default {
	journal: journal as { entries: { idx: number; when: number; tag: string; breakpoints: boolean }[] },
	files: {
		'0000_little_fallen_one': m0000,
	} as Record<string, string>,
};
