// @ts-nocheck
// Auto-generated by deskkit's gen-migrations — do not edit manually

import m0000 from '../drizzle/20260811083419_little_fallen_one/migration.sql' with { type: 'text' };

export default {
	migrations: [
		{ name: '20260811083419_little_fallen_one', sql: m0000 },
	],
};
